version: '1'
services:
    gateway:
        container_name: gateway
        build:
            context: gateway
            dockerfile: ./src/main/resources/Dockerfile
        image: gateway:latest
        ports:
            - 8080:8080
        depends_on:
            - kafka
        environment:
        - "SPRING_PROFILES_ACTIVE=dev"
        networks:
            - spring-cloud-network

    driver-service:
        container_name: driver-service
        build:
            context: driver
            dockerfile: ./src/main/resources/Dockerfile
        image: driver:latest
        ports:
            - 8081:8080
        depends_on:
            - kafka
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
        networks:
            - spring-cloud-network

    notifier-service:
        container_name: notifier-service
        build:
            context: notifier
            dockerfile: ./src/main/resources/Dockerfile
        image: notifier-service:latest
        ports:
            - 8082:8080
        depends_on:
            - kafka
        environment:
            - "SPRING_PROFILES_ACTIVE=dev"
        networks:
            - spring-cloud-network
    
    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
        networks:
            - spring-cloud-network
  
    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:29092
        environment:
            KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge